### ISSUE TITLE
fix column names to be consistent with database

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_names#20]
In the BWG database, we can upload all the taxa at once, but the names must be consistent.

EDIT: We still need to...
- [x] Set up the script to read in the latest version of `Distribution_organisms_full.tsv`
- [x] Number the script and output file when we know what order it goes in the script set
- [ ] Add the higher level taxonomic columns if Jonathan adds them to the database
- [ ] Add tribe and subspecies information for our species if we want it

**Comment by adletaw** [comment]
I added a script to do this. However, we are still missing some taxonomic columns from the database (those above Class).  Furthermore, there are some columns that we could be using (tribe, subspecies) but are not.  It would be best to have these two things sorted out before uploading, since the represent systemic problems rather than ones that could be solved on a species by species basis after uploading.

**Comment by adletaw** [comment]
The [script to do this](https://github.com/SrivastavaLab/bwg_names/blob/master/Rscripts/99_final_step_format_for_bwgdb.R) is ready.  We just need to add in the final changes made in [script 17](https://github.com/SrivastavaLab/bwg_names/blob/master/Rscripts/17_add_missing_traits.R).
