### ISSUE TITLE
Deal with duplicate rows

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwg_names#21]
Some rows have been duplicated in the dataset.  We should probably remove these, but @dsrivast can you confirm?  There are some issues here because sometimes the nicknames are slightly different between duplicate rows and we need to decide which one is correct.

Take a look at the full description in Andrew's excellent [report](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SrivastavaLab/bwg_names/master/report/report.html) under the heading `duplicates`.

**Comment by dsrivast** [comment]
I have pasted this comment from another issue. What happens if we later lump species, or discover true duplicates? We don't want duplicates (think of the potential of divergent "evolution" through researcher error in their functional traits), but I worry about how we would reliably change the BWG codes in the raw survey/precip data to match the chosen BWG name. @adletaw @aammd

**Comment by aammd** [comment]
hm. I just thought of this, but we already have a plan for handling synonymy: using the name1, name2 etc columns. Could that be a solution here?

**Comment by aammd** [comment]
Oh wait! I just looked back at the report (link above).  We are working with different definitions of "duplicates" -- here by "duplicate" I meant any rows with the *same nickname*. Thus nothing would have to change in the original datasets.
Rather it seems like trivial typos are the only differences.
 However, since there are one or two non-trivial differences (ie *Phylloicus bromeliarum* and Trichoptera.5602 are both nicknamed "Trichoptera.1") it seems best for somebody to resolve it (in this case, Trichoptera.5602 should probably go into the "name1" column of *Phyllocius bromeliarum*)
I'd like to suggest that @dsrivast decide what rows to create and destroy? :fire:

**Comment by dsrivast** [comment]
Yes, but is there a creative way to speed up @dsrivast's tasks? I am resolving a lot of things, and there isn't enough of me, I feel like I am once again becoming the rate-limiting step...especially with a trip to Costa Rica next week. Re Trichoptera - Argentina also found a Trichoptera, so I will need to make sure we don't confuse Cardoso's (identified) and Argentina's (unidentified) trichopteras.

**Comment by adletaw** [comment]
This issue could be resolved by anyone - it just takes a bit of reason and making a couple tough decisions that have no right answer.  @aammd is correct, any extra names and incorrect nicknames should be put in the `name1` `name2` etc. columns.  The fact that some species really do have the same nickname is a mistake that can't really be fixed, so we just need to make a decision on it, make a note of it, and move on.  I don't think those cases will have a major impact on anyone's published analyses because there are so few.

I suggest could @dsrivast assign this task to someone, and that person make careful documentation of what they do and why - and move any deprecated names into the extra name columns.

**Comment by aammd** [comment]
just had an in-person conversation with @dsrivast , summarizing here:

There are two cases we need to deal with:

1. Rows with identical `nickname` and identical `Name`
1. Rows with identical `nickname` but **different** `Name`

For **1**, @aammd will use R to compare the rows (with `identical`) to see if they are different. If not, will delete the odd-numbered ones. if they are different, will dispatch lab undergrads to track down where the changes originate.

Rows with **2** are more of an issue. Again, lab undergrads will be tasked with tracking down all of the first uses of each unique value of `Name` (Where does *Trichoptera.5602* come from, how many datasets use *Scirtes sp.1* with that exact spelling, etc). This will help us decide if two rows should be kept distinct or combined.

I will assign myself here, and open a new issue to give to @dsrivast (once back from CR) if that is necessary.

**Comment by aammd** [comment]
OK so the duplicate _Dero_ and _Elpidium_ from Serro do Japi are actually different species and should have different nicknames, as @dsrivast mentions in #32

**Comment by adletaw** [comment]
@aammd This issue has been solved, yes?

**Comment by aammd** [comment]
Aye, it was corrected with 469f572c3a48865624fc26d0fae773a9e45c9d02 , when `12_Distributions_organisms_full.tsv` was born. :persevere: closing
